### ISSUE TITLE
Feature request: Make Huntress be able to use auto-aim on players

### ISSUE THREAD

**Issue by Arctursus12** [tung362/RoR2PVP#10]
Her abilities are all unusable apart from Ballista/Arrow Rain, and makes PvP almost impossible

**Comment by tung362** [comment]
Hi, I can't seem to reproduce the problem you mention. I tested on both Free For All Mode and Teams PVP Mode along with modded and vanilla clients, both players on different teams were able to lock on to each other. Are you currently using any other mods? Some mods that change skills are known to not work for PVP due to them not taking into account PVP targeting.

You can deduct which mod is causing the conflict by running the game with just RoR2PVP installed along with the required libraries(BepInExPack & R2API) and see if huntress targeting still works, then slowly install your other mods and checking if targeting still works with each new mod install.
