### ISSUE TITLE
Config on r2modmanager is broken

### ISSUE THREAD

**Issue by Brent1056** [tung362/RoR2PVP#3]
on modmanager teampvp and teampvpcustominteractables config work fine but the other config files do not. (config menu shows nothing at all) witch is kinda annoying

**Comment by tung362** [comment]
TeamPVP.cfg and TeamPVPCustomInteractablesSpawner.cfg both uses the API's standard configuration structure which is why they work for the mod manager.

Due to how the config had to be structured for TeamPVPBannedItemList.cfg and TeamPVPCustomPlayableCharacters.cfg they are not structured like ones used by the API which is probably why it doesn't show up in the mod manager. I'd just manually edit them if it doesn't work in the manager.

Does the mod manager use a text editor? Or does it load the config and shows you all the field settings.

There's not much I can do on my end, you could request a text editor feature to be added to the mod manager for accepting more generic .cfg files. I believe mod managers like Vortex, Mod Organizer, Nexus Mod Manager does something like this (Unrelated).
