### ISSUE TITLE
Feature Request - Free For All mode

### ISSUE THREAD

**Issue by Sasurai087** [tung362/RoR2PVP#5]
Hello tung362! Thank you for implementing this mod. My friends and I thoroughly enjoy it and was wondering if you still plan to implement the FFA mode mentioned in your comment on Issue #1, March 23? Although we could simply turn on the friendly fire artifact, we enjoy your mod's grace timer feature and hidden enemy player names/HP bars. 

Please let me know if we simply overlooked this feature somewhere. I looked at the config files using R2modloader and did not see a function to enable FFA. Thanks again!

**Comment by tung362** [comment]
Hi!

I'm glad you're enjoying the mod :). Currently the mod does not have a FFA mode but is compatible with all the artifacts of the vanilla game including the friendly fire artifact as you already know.

To answer the question of if i'm planning to add a FFA mode or not is rather complicated. I have in the past attempted to add FFA to the mod (this was before artifacts was officially introduced into the game) but I dropped the idea due to a few reasons.
- **Compatibility:** This mod strives to be compatible with both modded clients and vanilla clients (IE: Modded and Vanilla players can pvp each other in public lobbies). As I looked through how teams and damage was set up I found it was done client sided which made it not possible for vanilla players to be assigned modded teams or change damage filtering so in order to make FFA work i'd have to force everyone to install the mod and be on modded clients only which went against my rule of compatibility.

- **A lot of messy code needed to make it work:** Most if not all the original code for teams was hard coded with restrictions, preventing new teams to be created without intercepting every function that had restrictions and removing them to accept new teams, I also don't think it would be great on performance doing that either. I also could just duplicate the class but anything changed within the original class would have to be monitored and adapted every time the game gets updated and major changes could break the whole system all together.

- **Friendly fire artifact got added:** With the artifacts being introduced to the vanilla game there was less incentive to add a FFA feature since the artifact was close enough to doing what was originally going to be intended. IE: You can get close to a FFA mode with the current mod but needs a few player self enforced rules like not going to the teleporter before every player had been killed (including your allies)

At the same time due to the friendly fire artifact being introduced into the game it *Might* be possible to create a FFA mode now that could solve all those reasons i mentioned. So the answer would be a maybe. If a FFA mode was to be created however the system would most likely run very different to how the current teams system that I have right now so it would most likely be a seperate mod. There is a lot of research that I still would have to look at to get a clearer conclusion.

 Anyways sorry I can't give you a clear answer D: it would be great if more people worked on pvp mods, i'm currently gather all the information myself and there really isn't much public information from other modders on this subject.

In my opinion though, it is absolutely 100% possible to create a FFA mod, it's just what you have to sacrifice to make it.

**Comment by Sasurai087** [comment]
Thank you for the swift and detailed response! I admire and respect your rule of compatibility and will relay this information over to my friends.  I agree that it would be nice to have more PVP mods as well, but kudos to you for being the trailblazer! We will continue tinkering with the mod and the friendly-fire artifact, along with self-enforced rules per your suggestion.

**Comment by tung362** [comment]
Hey,
Just an update, I'm currently looking into making a FFA mode again, I found some leads that just might this work out.

**Comment by tung362** [comment]
Hey,
Free For All will be added soon! As predicted with the addition of artifacts opened a new route to solving the block

**Comment by Sasurai087** [comment]
Wow that's incredible! Please keep us posted - my friends and I are definitely interested in trying it out. Then I can finally show them why I'm objectively the best among them. :P

**Comment by tung362** [comment]
The new version is released! Note that the mod has moved mod pages to this new one https://thunderstore.io/package/60dfb16d5e944afc/RoR2PVP/
