### ISSUE TITLE
Feature request - PlayerBots compatibility

### ISSUE THREAD

**Issue by metalmechsolid** [tung362/RoR2PVP#6]
Remove friends as a requirement!
https://thunderstore.io/package/Meledy/PlayerBots/
For the most part, everything works when i spawn in the bots (after changing them to show up as players in it's config) but i notice nobody's dio's bears lower when they die. I've tried in both singleplayer and multiplayer but it's the same.

**Comment by tung362** [comment]
Hey!
Thanks for requesting a feature :) Doing some investigation the infinite dio is most likely due to a code sequence never reaching a trigger end point because of an error which causes the same give dio item code to run over and over again. I do like the idea of having AI participate in pvp and I do believe both mods would synergize very well with each other, who needs friends anyways am I right? As a way to fill this loneliness within my heart I'll look into what I can do to make both mods compatible! I can't promise anything though 🤷

**Comment by tung362** [comment]
I haven't had much time to work on it today but I did fix most of the issues, there's still a few things I need to tweak before a release can be made. I also been talking to the mod author, a pretty cool person :D

Anyways here's a preview: https://youtu.be/a9G1v51GITQ

**Comment by tung362** [comment]
The new version is released, PlayerBots should be compatible now!
Note that there's still things that can be improved such as being able to tell where every bot is at all time etc etc, so you might be running around for awhile finding the last enemy who might be stuck since you sometimes can't see their name tags.
