### ISSUE TITLE
Projectile Problems

### ISSUE THREAD

**Issue by Zandy5** [tung362/RoR2PVP#8]
Hello! My friends and I are loving your mod, but we have run into a few problems: 

Rex's projectile abilities (His primary, secondary, and special) Are not working for us. My friend tries to use those abilities, but nothing happens but the sound effect.

Loader's grapple ability seems to stop working when there are two of the three of us left alive.

Captain's projectiles also don't work, so his secondary and his shift. 

No idea why these would be the case, but yeah. Also, super looking forward to a FFA mode! We just have three of us, so that will be immensely useful.

**Comment by tung362** [comment]
Hi!

I'm glad you guys are enjoying the mod! I can't seem to reproduce those problems you mentioned with another client, are you guys using any other mods? Also is there any errors in the console window when you shoot those projectiles? If you can provide me a list of the mods you're using or some screenshots of errors in the console window I can try investigating the cause of the problem.

Here's a preview of the next release: https://imgur.com/lTArmWi
I'm currently trying to move a lot of the major settings (team picker, custom playable characters, banned items) over to the new UI system to be modified in-game instead of having to exit the game and modifying the .cfg files. After all that is done I'll have to do a lot of testing to make sure everything works as intended then I'll be able to release. I estimate it will take me 1-3 more days maybe

**Comment by Zandy5** [comment]
We are using several other mods, but the main one that I could see causing a problem might be Skills+++? The fill list is:
Sniper
ArtificerExtended
BanditReloaded
BetterCommandMenu
BetterUI
Diluvian
EmptyChestsBegone
Enforcer
EscapeFromMenus
Faster3dPrinters
PauseInMultiplayer
Propersave
RogueWisp
and Skills+++

**Comment by tung362** [comment]
Hmm I still can't reproduce the bugs seems be to working fine to me, was it something that happened late in the run? Or did it happen right at the start of the run? Was there any specific modded characters you guys were playing? Were you playing any modded difficulty? If it's late in the run that might be hard to find the cause... Best advice I can give you is if the problem keeps occurring you could try disabling mods one at a time through trial and error to figure out what's the conflict, for all we know it might not even be my mod that's causing the conflicts. Sorry I couldn't be more of a help D:

**Comment by Zandy5** [comment]
Heyo! So, I figured it out. It was a problem on Rex, Bandit, Captain, Loader, Mercenary, and I think that was it, but only when the other players tried those characters. When I (the host) played them, they worked perfectly.

**Comment by Zandy5** [comment]
So, to be clear, I figured out what exactly the problem was, not how to fix it.

**Comment by tung362** [comment]
Hi,

I still can't replicate the bug you mentioned, I tried both characters using custom characters(sniper), I also tried both characters being Rex but projectiles seem to be working fine to me. Heres a screenshot, this was taken in the 3rd round with the host being the other client
https://i.imgur.com/gDeAe09.gif

My guess would be the mod that lets you unlock skills (I don't remember the name) might be causing some problems but I'm not certain.

**Comment by tung362** [comment]
If you'd like we could schedule a test session at some point, just send me here or an email with your steam or discord to schedule a time.

**Comment by Zandy5** [comment]
Yep! Skills++ was the problem. Thanks!
