### ISSUE TITLE
Cash granting not working.

### ISSUE THREAD

**Issue by Jone6552** [tung362/RoR2PVP#9]
Me and a few friends use the pvp mod to face off against each other, but we are unable to get any money through the cash grant system. Unless we have mobs on to kill for money, we still have 0 by the time the pvp starts. We've tried running with both mods on and a clean profile with just the pvp mod.

**Comment by tung362** [comment]
Hi!

I can't seem seem to recreate the bug you mentioned while testing with another client, money grant seems to be working fine. If you changed the configs in any way make sure to check for no extra spacing, no tabs, and no invalid values which all might cause unexpected problems. You can also reset your config by deleting the old one and the mod will generate you a new one with all the default values.

Are you by any chance using the ShareSuite mod? The pvp mod is partially incompatible with that mod due to it completely overriding the vanilla money grant method which the pvp mod uses for granting players money.
